on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Example calling an action from different repo
    steps:
      - id: foo
        uses: TizianHoffmann/actions-demo/my-simple-action@dev-composite-action
        with:
          message: 'Input from elsewhere'